---
type: showroom

# Set the left column width to 30%
default_width: 30
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  # OpenShift Console
  - name: OpenShift Console
    url: '{openshift_console_url}'

  # Migration Toolkit for Applications
  - name: MTA
    url: 'https://mta-{openshift_cluster_ingress_domain}'

  # Red Hat OpenShift Dev Spaces
  - name: Dev Spaces
    url: 'https://devspaces-{openshift_cluster_ingress_domain}'

  # Gitea
  - name: Gitea
    url: 'https://gitea-{openshift_cluster_ingress_domain}'
