---
apiVersion: v1
kind: BuildConfig
metadata:
  name: showroom-solver
  namespace: user-sct29-showroom
spec:
  output:
    to:
      kind: ImageStreamTag
      name: showroom-solver:latest
  source:
    type: Git
    git:
      uri: https://github.com/rhpds/rhads-ols-modernize-showroom.git
      ref: poc-solve-button-realtime
    contextDir: runtime-automation
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  triggers:
    - type: ConfigChange
    - type: ImageChange
---
apiVersion: v1
kind: ImageStream
metadata:
  name: showroom-solver
  namespace: user-sct29-showroom
spec:
  lookupPolicy:
    local: true
